# Generated by Django 2.1.4 on 2018-12-27 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20181227_0907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
