# Generated by Django 2.1.4 on 2018-12-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_delete_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-created_date_time', 'title']},
        ),
    ]
