# Generated by Django 2.1.4 on 2018-12-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180616_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
